#!/usr/bin/env python

#Author: Arturo Cruz Maya 


import roslib; roslib.load_manifest('anomaly_detector')
import rospy
from std_msgs.msg import String
from anomaly_detector.msg import Joint
import qi
import time
import argparse
import sys
import numpy as np
import threading


class AnomalyDetector:
    """
    A class to collect data from the sensors and send it through ROS
    """

    def __init__(self, session):
    	self.memory = session.service("ALMemory")
        self.motion = session.service("ALMotion")
        self.tts = session.service("ALTextToSpeech")
        self.joints={}
        self.imu={}
        self.pub_joint = rospy.Publisher('/anomaly', Joint, queue_size=1)
        self.sub_collision = rospy.Subscriber('/collision', String, self.callback_collision)
        self.time_init = time.time()
        self.run()

    def callback_collision(self, data):
        if (time.time() - self.time_init) > 2:
            self.time_init = time.time()
            self.tts.say("ow")

    def getData(self, joint):
        PositionActuator =  self.memory.getData("Device/SubDeviceList/"+joint+"/Position/Actuator/Value")
        PositionSensor =  self.memory.getData("Device/SubDeviceList/"+joint+"/Position/Sensor/Value")
        ElectricCurrent =  self.memory.getData("Device/SubDeviceList/"+joint+"/ElectricCurrent/Sensor/Value")
        TemperatureSensor =  self.memory.getData("Device/SubDeviceList/"+joint+"/Temperature/Sensor/Value")
        Hardness =  self.memory.getData("Device/SubDeviceList/"+joint+"/Hardness/Actuator/Value")
        TemperatureStatus =  self.memory.getData("Device/SubDeviceList/"+joint+"/Temperature/Sensor/Status")
         
        self.joints[joint][0].append(round(PositionActuator,6))
        self.joints[joint][1].append(round(PositionSensor,6))	
        self.joints[joint][2].append(round(ElectricCurrent,6))
        self.joints[joint][3].append(round(TemperatureSensor,6))
        self.joints[joint][4].append(round(Hardness,6))
        self.joints[joint][5].append(round(TemperatureStatus,6))	

        
        joint = Joint() 
        joint.commanded_position = float(PositionActuator)
        joint.sensed_position = float(PositionSensor) 
        self.pub_joint.publish(joint)        

        #print "####################"
        return True 

    def getDataIMU(self, sensor):
        X =  self.memory.getData("Device/SubDeviceList/InertialSensorBase/"+sensor+"X/Sensor/Value")
        Y =  self.memory.getData("Device/SubDeviceList/InertialSensorBase/"+sensor+"Y/Sensor/Value")
        Z =  self.memory.getData("Device/SubDeviceList/InertialSensorBase/"+sensor+"Z/Sensor/Value")
         
        self.imu[sensor][0].append(round(X,6))
        self.imu[sensor][1].append(round(Y,6))	
        self.imu[sensor][2].append(round(Z,6))

        #print "####################"
        return True 

    def save_txt(self, joint):

        np.savetxt("txt/"+joint+".txt", np.transpose(self.joints[joint]), fmt='%f', delimiter='  ', newline='\n', header='', footer='', comments='# ', encoding=None)

			
    def run(self):
        """
        Loop on, wait for events until manual interruption.
        """
        print "Starting Collecting Data (sensors)"
        try:
            joints = []
            sensors = []   	
            #Head
            joints.append('HeadPitch')
            '''   
            joints.append('HeadYaw')
            #RArm
            joints.append('RShoulderRoll')
            joints.append('RShoulderPitch')
            joints.append('RElbowYaw')
            joints.append('RElbowRoll')
            joints.append('RHand')
            #LArm
            joints.append('LShoulderRoll')
            joints.append('LShoulderPitch')
            joints.append('LElbowYaw')
            joints.append('LElbowRoll')
            joints.append('LHand')
            #Leg
            joints.append('HipPitch')
            joints.append('HipRoll')
            joints.append('KneePitch')
            #IMU	
            sensors.append('Gyroscope')
            sensors.append('Angle')	
            sensors.append('Accelerometer')
            ''' 
        	
           
            for joint in joints:
                self.joints[joint]=[[],[],[],[],[],[]]
            for sensor in sensors:
                self.imu[sensor]=[[],[],[]]
            
            n = 0

            while True:
                for joint in joints:
                    time.sleep(0.2)
                    self.getData(joint)
                #for sensor in sensors:
                #    self.getDataIMU(sensor)
                print n
                #self.publisher.publish(str(n))
                n = n + 1
            print "Finished"
        except KeyboardInterrupt:
            print "Interrupted by user, stopping Collecting Data"
           
            sys.exit(0)


def main():
    rospy.init_node('anomaly_detector')
    
    app = qi.Application(url="tcp://10.0.205.33:9559")
    app.start()
    session = app.session
    anomaly_detector = AnomalyDetector(session)

    session.registerService('AnomalyDetector', anomaly_detector)
    
    app.run()
 
    	

if __name__ == '__main__':
    main()
